
create table PESSOA  (
      ID INT (2) NOT NULL PRIMARY KEY  AUTO_INCREMENT ,
      NOME VARCHAR(50) NOT NULL,
      CPF VARCHAR(11) NOT NULL UNIQUE,
      IDADE INT(3) NOT NULL,
      TELEFONE VARCHAR(11) NULL
      )